// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/state_datas.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_proto_2fstate_5fdatas_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_proto_2fstate_5fdatas_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_proto_2fstate_5fdatas_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2fstate_5fdatas_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2fstate_5fdatas_2eproto;
namespace quadruped {
class BatteryState;
class BatteryStateDefaultTypeInternal;
extern BatteryStateDefaultTypeInternal _BatteryState_default_instance_;
class BodyLocation;
class BodyLocationDefaultTypeInternal;
extern BodyLocationDefaultTypeInternal _BodyLocation_default_instance_;
class GlobalLocation;
class GlobalLocationDefaultTypeInternal;
extern GlobalLocationDefaultTypeInternal _GlobalLocation_default_instance_;
class IMUState;
class IMUStateDefaultTypeInternal;
extern IMUStateDefaultTypeInternal _IMUState_default_instance_;
class StateDatas;
class StateDatasDefaultTypeInternal;
extern StateDatasDefaultTypeInternal _StateDatas_default_instance_;
}  // namespace quadruped
PROTOBUF_NAMESPACE_OPEN
template<> ::quadruped::BatteryState* Arena::CreateMaybeMessage<::quadruped::BatteryState>(Arena*);
template<> ::quadruped::BodyLocation* Arena::CreateMaybeMessage<::quadruped::BodyLocation>(Arena*);
template<> ::quadruped::GlobalLocation* Arena::CreateMaybeMessage<::quadruped::GlobalLocation>(Arena*);
template<> ::quadruped::IMUState* Arena::CreateMaybeMessage<::quadruped::IMUState>(Arena*);
template<> ::quadruped::StateDatas* Arena::CreateMaybeMessage<::quadruped::StateDatas>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace quadruped {

// ===================================================================

class BatteryState PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:quadruped.BatteryState) */ {
 public:
  inline BatteryState() : BatteryState(nullptr) {}
  virtual ~BatteryState();

  BatteryState(const BatteryState& from);
  BatteryState(BatteryState&& from) noexcept
    : BatteryState() {
    *this = ::std::move(from);
  }

  inline BatteryState& operator=(const BatteryState& from) {
    CopyFrom(from);
    return *this;
  }
  inline BatteryState& operator=(BatteryState&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const BatteryState& default_instance();

  static inline const BatteryState* internal_default_instance() {
    return reinterpret_cast<const BatteryState*>(
               &_BatteryState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(BatteryState& a, BatteryState& b) {
    a.Swap(&b);
  }
  inline void Swap(BatteryState* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BatteryState* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline BatteryState* New() const final {
    return CreateMaybeMessage<BatteryState>(nullptr);
  }

  BatteryState* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<BatteryState>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const BatteryState& from);
  void MergeFrom(const BatteryState& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BatteryState* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "quadruped.BatteryState";
  }
  protected:
  explicit BatteryState(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_proto_2fstate_5fdatas_2eproto);
    return ::descriptor_table_proto_2fstate_5fdatas_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStatusFieldNumber = 1,
    kSocFieldNumber = 2,
    kCurrentFieldNumber = 3,
    kCycleFieldNumber = 4,
  };
  // optional int32 status = 1;
  bool has_status() const;
  private:
  bool _internal_has_status() const;
  public:
  void clear_status();
  ::PROTOBUF_NAMESPACE_ID::int32 status() const;
  void set_status(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_status() const;
  void _internal_set_status(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // optional int32 soc = 2;
  bool has_soc() const;
  private:
  bool _internal_has_soc() const;
  public:
  void clear_soc();
  ::PROTOBUF_NAMESPACE_ID::int32 soc() const;
  void set_soc(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_soc() const;
  void _internal_set_soc(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // optional int32 current = 3;
  bool has_current() const;
  private:
  bool _internal_has_current() const;
  public:
  void clear_current();
  ::PROTOBUF_NAMESPACE_ID::int32 current() const;
  void set_current(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_current() const;
  void _internal_set_current(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // optional int32 cycle = 4;
  bool has_cycle() const;
  private:
  bool _internal_has_cycle() const;
  public:
  void clear_cycle();
  ::PROTOBUF_NAMESPACE_ID::int32 cycle() const;
  void set_cycle(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_cycle() const;
  void _internal_set_cycle(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:quadruped.BatteryState)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::int32 status_;
  ::PROTOBUF_NAMESPACE_ID::int32 soc_;
  ::PROTOBUF_NAMESPACE_ID::int32 current_;
  ::PROTOBUF_NAMESPACE_ID::int32 cycle_;
  friend struct ::TableStruct_proto_2fstate_5fdatas_2eproto;
};
// -------------------------------------------------------------------

class IMUState PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:quadruped.IMUState) */ {
 public:
  inline IMUState() : IMUState(nullptr) {}
  virtual ~IMUState();

  IMUState(const IMUState& from);
  IMUState(IMUState&& from) noexcept
    : IMUState() {
    *this = ::std::move(from);
  }

  inline IMUState& operator=(const IMUState& from) {
    CopyFrom(from);
    return *this;
  }
  inline IMUState& operator=(IMUState&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const IMUState& default_instance();

  static inline const IMUState* internal_default_instance() {
    return reinterpret_cast<const IMUState*>(
               &_IMUState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(IMUState& a, IMUState& b) {
    a.Swap(&b);
  }
  inline void Swap(IMUState* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IMUState* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline IMUState* New() const final {
    return CreateMaybeMessage<IMUState>(nullptr);
  }

  IMUState* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<IMUState>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const IMUState& from);
  void MergeFrom(const IMUState& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IMUState* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "quadruped.IMUState";
  }
  protected:
  explicit IMUState(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_proto_2fstate_5fdatas_2eproto);
    return ::descriptor_table_proto_2fstate_5fdatas_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kQuaternionFieldNumber = 1,
    kGyroscopeFieldNumber = 2,
    kAccelerometerFieldNumber = 3,
    kRpyFieldNumber = 4,
    kTemperatureFieldNumber = 5,
  };
  // repeated float quaternion = 1 [packed = true];
  int quaternion_size() const;
  private:
  int _internal_quaternion_size() const;
  public:
  void clear_quaternion();
  private:
  float _internal_quaternion(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_quaternion() const;
  void _internal_add_quaternion(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_quaternion();
  public:
  float quaternion(int index) const;
  void set_quaternion(int index, float value);
  void add_quaternion(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      quaternion() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_quaternion();

  // repeated float gyroscope = 2 [packed = true];
  int gyroscope_size() const;
  private:
  int _internal_gyroscope_size() const;
  public:
  void clear_gyroscope();
  private:
  float _internal_gyroscope(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_gyroscope() const;
  void _internal_add_gyroscope(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_gyroscope();
  public:
  float gyroscope(int index) const;
  void set_gyroscope(int index, float value);
  void add_gyroscope(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      gyroscope() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_gyroscope();

  // repeated float accelerometer = 3 [packed = true];
  int accelerometer_size() const;
  private:
  int _internal_accelerometer_size() const;
  public:
  void clear_accelerometer();
  private:
  float _internal_accelerometer(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_accelerometer() const;
  void _internal_add_accelerometer(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_accelerometer();
  public:
  float accelerometer(int index) const;
  void set_accelerometer(int index, float value);
  void add_accelerometer(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      accelerometer() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_accelerometer();

  // repeated float rpy = 4 [packed = true];
  int rpy_size() const;
  private:
  int _internal_rpy_size() const;
  public:
  void clear_rpy();
  private:
  float _internal_rpy(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_rpy() const;
  void _internal_add_rpy(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_rpy();
  public:
  float rpy(int index) const;
  void set_rpy(int index, float value);
  void add_rpy(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      rpy() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_rpy();

  // optional int32 temperature = 5;
  bool has_temperature() const;
  private:
  bool _internal_has_temperature() const;
  public:
  void clear_temperature();
  ::PROTOBUF_NAMESPACE_ID::int32 temperature() const;
  void set_temperature(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_temperature() const;
  void _internal_set_temperature(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:quadruped.IMUState)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > quaternion_;
  mutable std::atomic<int> _quaternion_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > gyroscope_;
  mutable std::atomic<int> _gyroscope_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > accelerometer_;
  mutable std::atomic<int> _accelerometer_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > rpy_;
  mutable std::atomic<int> _rpy_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::int32 temperature_;
  friend struct ::TableStruct_proto_2fstate_5fdatas_2eproto;
};
// -------------------------------------------------------------------

class GlobalLocation PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:quadruped.GlobalLocation) */ {
 public:
  inline GlobalLocation() : GlobalLocation(nullptr) {}
  virtual ~GlobalLocation();

  GlobalLocation(const GlobalLocation& from);
  GlobalLocation(GlobalLocation&& from) noexcept
    : GlobalLocation() {
    *this = ::std::move(from);
  }

  inline GlobalLocation& operator=(const GlobalLocation& from) {
    CopyFrom(from);
    return *this;
  }
  inline GlobalLocation& operator=(GlobalLocation&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GlobalLocation& default_instance();

  static inline const GlobalLocation* internal_default_instance() {
    return reinterpret_cast<const GlobalLocation*>(
               &_GlobalLocation_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(GlobalLocation& a, GlobalLocation& b) {
    a.Swap(&b);
  }
  inline void Swap(GlobalLocation* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GlobalLocation* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GlobalLocation* New() const final {
    return CreateMaybeMessage<GlobalLocation>(nullptr);
  }

  GlobalLocation* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GlobalLocation>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GlobalLocation& from);
  void MergeFrom(const GlobalLocation& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GlobalLocation* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "quadruped.GlobalLocation";
  }
  protected:
  explicit GlobalLocation(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_proto_2fstate_5fdatas_2eproto);
    return ::descriptor_table_proto_2fstate_5fdatas_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPositionFieldNumber = 1,
    kVelocityFieldNumber = 2,
    kYawSpeedFieldNumber = 3,
  };
  // repeated float position = 1 [packed = true];
  int position_size() const;
  private:
  int _internal_position_size() const;
  public:
  void clear_position();
  private:
  float _internal_position(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_position() const;
  void _internal_add_position(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_position();
  public:
  float position(int index) const;
  void set_position(int index, float value);
  void add_position(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      position() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_position();

  // repeated float velocity = 2 [packed = true];
  int velocity_size() const;
  private:
  int _internal_velocity_size() const;
  public:
  void clear_velocity();
  private:
  float _internal_velocity(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_velocity() const;
  void _internal_add_velocity(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_velocity();
  public:
  float velocity(int index) const;
  void set_velocity(int index, float value);
  void add_velocity(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      velocity() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_velocity();

  // optional float yaw_speed = 3;
  bool has_yaw_speed() const;
  private:
  bool _internal_has_yaw_speed() const;
  public:
  void clear_yaw_speed();
  float yaw_speed() const;
  void set_yaw_speed(float value);
  private:
  float _internal_yaw_speed() const;
  void _internal_set_yaw_speed(float value);
  public:

  // @@protoc_insertion_point(class_scope:quadruped.GlobalLocation)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > position_;
  mutable std::atomic<int> _position_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > velocity_;
  mutable std::atomic<int> _velocity_cached_byte_size_;
  float yaw_speed_;
  friend struct ::TableStruct_proto_2fstate_5fdatas_2eproto;
};
// -------------------------------------------------------------------

class BodyLocation PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:quadruped.BodyLocation) */ {
 public:
  inline BodyLocation() : BodyLocation(nullptr) {}
  virtual ~BodyLocation();

  BodyLocation(const BodyLocation& from);
  BodyLocation(BodyLocation&& from) noexcept
    : BodyLocation() {
    *this = ::std::move(from);
  }

  inline BodyLocation& operator=(const BodyLocation& from) {
    CopyFrom(from);
    return *this;
  }
  inline BodyLocation& operator=(BodyLocation&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const BodyLocation& default_instance();

  static inline const BodyLocation* internal_default_instance() {
    return reinterpret_cast<const BodyLocation*>(
               &_BodyLocation_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(BodyLocation& a, BodyLocation& b) {
    a.Swap(&b);
  }
  inline void Swap(BodyLocation* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BodyLocation* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline BodyLocation* New() const final {
    return CreateMaybeMessage<BodyLocation>(nullptr);
  }

  BodyLocation* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<BodyLocation>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const BodyLocation& from);
  void MergeFrom(const BodyLocation& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BodyLocation* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "quadruped.BodyLocation";
  }
  protected:
  explicit BodyLocation(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_proto_2fstate_5fdatas_2eproto);
    return ::descriptor_table_proto_2fstate_5fdatas_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFootForceFieldNumber = 1,
    kFootPositionBodyFieldNumber = 3,
    kFootSpeedBodyFieldNumber = 4,
    kBodyHeightFieldNumber = 2,
  };
  // repeated int32 foot_force = 1 [packed = true];
  int foot_force_size() const;
  private:
  int _internal_foot_force_size() const;
  public:
  void clear_foot_force();
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_foot_force(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
      _internal_foot_force() const;
  void _internal_add_foot_force(::PROTOBUF_NAMESPACE_ID::int32 value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
      _internal_mutable_foot_force();
  public:
  ::PROTOBUF_NAMESPACE_ID::int32 foot_force(int index) const;
  void set_foot_force(int index, ::PROTOBUF_NAMESPACE_ID::int32 value);
  void add_foot_force(::PROTOBUF_NAMESPACE_ID::int32 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
      foot_force() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
      mutable_foot_force();

  // repeated float foot_position_body = 3 [packed = true];
  int foot_position_body_size() const;
  private:
  int _internal_foot_position_body_size() const;
  public:
  void clear_foot_position_body();
  private:
  float _internal_foot_position_body(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_foot_position_body() const;
  void _internal_add_foot_position_body(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_foot_position_body();
  public:
  float foot_position_body(int index) const;
  void set_foot_position_body(int index, float value);
  void add_foot_position_body(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      foot_position_body() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_foot_position_body();

  // repeated float foot_speed_body = 4 [packed = true];
  int foot_speed_body_size() const;
  private:
  int _internal_foot_speed_body_size() const;
  public:
  void clear_foot_speed_body();
  private:
  float _internal_foot_speed_body(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_foot_speed_body() const;
  void _internal_add_foot_speed_body(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_foot_speed_body();
  public:
  float foot_speed_body(int index) const;
  void set_foot_speed_body(int index, float value);
  void add_foot_speed_body(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      foot_speed_body() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_foot_speed_body();

  // optional float body_height = 2;
  bool has_body_height() const;
  private:
  bool _internal_has_body_height() const;
  public:
  void clear_body_height();
  float body_height() const;
  void set_body_height(float value);
  private:
  float _internal_body_height() const;
  void _internal_set_body_height(float value);
  public:

  // @@protoc_insertion_point(class_scope:quadruped.BodyLocation)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 > foot_force_;
  mutable std::atomic<int> _foot_force_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > foot_position_body_;
  mutable std::atomic<int> _foot_position_body_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > foot_speed_body_;
  mutable std::atomic<int> _foot_speed_body_cached_byte_size_;
  float body_height_;
  friend struct ::TableStruct_proto_2fstate_5fdatas_2eproto;
};
// -------------------------------------------------------------------

class StateDatas PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:quadruped.StateDatas) */ {
 public:
  inline StateDatas() : StateDatas(nullptr) {}
  virtual ~StateDatas();

  StateDatas(const StateDatas& from);
  StateDatas(StateDatas&& from) noexcept
    : StateDatas() {
    *this = ::std::move(from);
  }

  inline StateDatas& operator=(const StateDatas& from) {
    CopyFrom(from);
    return *this;
  }
  inline StateDatas& operator=(StateDatas&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const StateDatas& default_instance();

  static inline const StateDatas* internal_default_instance() {
    return reinterpret_cast<const StateDatas*>(
               &_StateDatas_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(StateDatas& a, StateDatas& b) {
    a.Swap(&b);
  }
  inline void Swap(StateDatas* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StateDatas* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline StateDatas* New() const final {
    return CreateMaybeMessage<StateDatas>(nullptr);
  }

  StateDatas* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<StateDatas>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const StateDatas& from);
  void MergeFrom(const StateDatas& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StateDatas* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "quadruped.StateDatas";
  }
  protected:
  explicit StateDatas(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_proto_2fstate_5fdatas_2eproto);
    return ::descriptor_table_proto_2fstate_5fdatas_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSportModeFieldNumber = 2,
    kBatteryStateFieldNumber = 7,
    kImuStateFieldNumber = 8,
    kGlobalLocationFieldNumber = 9,
    kBodyLocationFieldNumber = 10,
    kObstacleAvoidModeFieldNumber = 1,
    kHighLevelModeFieldNumber = 3,
    kFootRaiseHeightFieldNumber = 5,
    kGaitTypeFieldNumber = 6,
  };
  // optional string sport_mode = 2 [default = "normal"];
  bool has_sport_mode() const;
  private:
  bool _internal_has_sport_mode() const;
  public:
  void clear_sport_mode();
  const std::string& sport_mode() const;
  void set_sport_mode(const std::string& value);
  void set_sport_mode(std::string&& value);
  void set_sport_mode(const char* value);
  void set_sport_mode(const char* value, size_t size);
  std::string* mutable_sport_mode();
  std::string* release_sport_mode();
  void set_allocated_sport_mode(std::string* sport_mode);
  private:
  const std::string& _internal_sport_mode() const;
  void _internal_set_sport_mode(const std::string& value);
  std::string* _internal_mutable_sport_mode();
  public:

  // optional .quadruped.BatteryState battery_state = 7;
  bool has_battery_state() const;
  private:
  bool _internal_has_battery_state() const;
  public:
  void clear_battery_state();
  const ::quadruped::BatteryState& battery_state() const;
  ::quadruped::BatteryState* release_battery_state();
  ::quadruped::BatteryState* mutable_battery_state();
  void set_allocated_battery_state(::quadruped::BatteryState* battery_state);
  private:
  const ::quadruped::BatteryState& _internal_battery_state() const;
  ::quadruped::BatteryState* _internal_mutable_battery_state();
  public:
  void unsafe_arena_set_allocated_battery_state(
      ::quadruped::BatteryState* battery_state);
  ::quadruped::BatteryState* unsafe_arena_release_battery_state();

  // optional .quadruped.IMUState imu_state = 8;
  bool has_imu_state() const;
  private:
  bool _internal_has_imu_state() const;
  public:
  void clear_imu_state();
  const ::quadruped::IMUState& imu_state() const;
  ::quadruped::IMUState* release_imu_state();
  ::quadruped::IMUState* mutable_imu_state();
  void set_allocated_imu_state(::quadruped::IMUState* imu_state);
  private:
  const ::quadruped::IMUState& _internal_imu_state() const;
  ::quadruped::IMUState* _internal_mutable_imu_state();
  public:
  void unsafe_arena_set_allocated_imu_state(
      ::quadruped::IMUState* imu_state);
  ::quadruped::IMUState* unsafe_arena_release_imu_state();

  // optional .quadruped.GlobalLocation global_location = 9;
  bool has_global_location() const;
  private:
  bool _internal_has_global_location() const;
  public:
  void clear_global_location();
  const ::quadruped::GlobalLocation& global_location() const;
  ::quadruped::GlobalLocation* release_global_location();
  ::quadruped::GlobalLocation* mutable_global_location();
  void set_allocated_global_location(::quadruped::GlobalLocation* global_location);
  private:
  const ::quadruped::GlobalLocation& _internal_global_location() const;
  ::quadruped::GlobalLocation* _internal_mutable_global_location();
  public:
  void unsafe_arena_set_allocated_global_location(
      ::quadruped::GlobalLocation* global_location);
  ::quadruped::GlobalLocation* unsafe_arena_release_global_location();

  // optional .quadruped.BodyLocation body_location = 10;
  bool has_body_location() const;
  private:
  bool _internal_has_body_location() const;
  public:
  void clear_body_location();
  const ::quadruped::BodyLocation& body_location() const;
  ::quadruped::BodyLocation* release_body_location();
  ::quadruped::BodyLocation* mutable_body_location();
  void set_allocated_body_location(::quadruped::BodyLocation* body_location);
  private:
  const ::quadruped::BodyLocation& _internal_body_location() const;
  ::quadruped::BodyLocation* _internal_mutable_body_location();
  public:
  void unsafe_arena_set_allocated_body_location(
      ::quadruped::BodyLocation* body_location);
  ::quadruped::BodyLocation* unsafe_arena_release_body_location();

  // optional bool obstacle_avoid_mode = 1 [default = false];
  bool has_obstacle_avoid_mode() const;
  private:
  bool _internal_has_obstacle_avoid_mode() const;
  public:
  void clear_obstacle_avoid_mode();
  bool obstacle_avoid_mode() const;
  void set_obstacle_avoid_mode(bool value);
  private:
  bool _internal_obstacle_avoid_mode() const;
  void _internal_set_obstacle_avoid_mode(bool value);
  public:

  // optional int32 high_level_mode = 3 [default = 0];
  bool has_high_level_mode() const;
  private:
  bool _internal_has_high_level_mode() const;
  public:
  void clear_high_level_mode();
  ::PROTOBUF_NAMESPACE_ID::int32 high_level_mode() const;
  void set_high_level_mode(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_high_level_mode() const;
  void _internal_set_high_level_mode(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // optional float foot_raise_height = 5 [default = 0];
  bool has_foot_raise_height() const;
  private:
  bool _internal_has_foot_raise_height() const;
  public:
  void clear_foot_raise_height();
  float foot_raise_height() const;
  void set_foot_raise_height(float value);
  private:
  float _internal_foot_raise_height() const;
  void _internal_set_foot_raise_height(float value);
  public:

  // optional int32 gait_type = 6 [default = 0];
  bool has_gait_type() const;
  private:
  bool _internal_has_gait_type() const;
  public:
  void clear_gait_type();
  ::PROTOBUF_NAMESPACE_ID::int32 gait_type() const;
  void set_gait_type(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_gait_type() const;
  void _internal_set_gait_type(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:quadruped.StateDatas)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  static const ::PROTOBUF_NAMESPACE_ID::internal::LazyString _i_give_permission_to_break_this_code_default_sport_mode_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sport_mode_;
  ::quadruped::BatteryState* battery_state_;
  ::quadruped::IMUState* imu_state_;
  ::quadruped::GlobalLocation* global_location_;
  ::quadruped::BodyLocation* body_location_;
  bool obstacle_avoid_mode_;
  ::PROTOBUF_NAMESPACE_ID::int32 high_level_mode_;
  float foot_raise_height_;
  ::PROTOBUF_NAMESPACE_ID::int32 gait_type_;
  friend struct ::TableStruct_proto_2fstate_5fdatas_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BatteryState

// optional int32 status = 1;
inline bool BatteryState::_internal_has_status() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool BatteryState::has_status() const {
  return _internal_has_status();
}
inline void BatteryState::clear_status() {
  status_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 BatteryState::_internal_status() const {
  return status_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 BatteryState::status() const {
  // @@protoc_insertion_point(field_get:quadruped.BatteryState.status)
  return _internal_status();
}
inline void BatteryState::_internal_set_status(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000001u;
  status_ = value;
}
inline void BatteryState::set_status(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:quadruped.BatteryState.status)
}

// optional int32 soc = 2;
inline bool BatteryState::_internal_has_soc() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool BatteryState::has_soc() const {
  return _internal_has_soc();
}
inline void BatteryState::clear_soc() {
  soc_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 BatteryState::_internal_soc() const {
  return soc_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 BatteryState::soc() const {
  // @@protoc_insertion_point(field_get:quadruped.BatteryState.soc)
  return _internal_soc();
}
inline void BatteryState::_internal_set_soc(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  soc_ = value;
}
inline void BatteryState::set_soc(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_soc(value);
  // @@protoc_insertion_point(field_set:quadruped.BatteryState.soc)
}

// optional int32 current = 3;
inline bool BatteryState::_internal_has_current() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool BatteryState::has_current() const {
  return _internal_has_current();
}
inline void BatteryState::clear_current() {
  current_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 BatteryState::_internal_current() const {
  return current_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 BatteryState::current() const {
  // @@protoc_insertion_point(field_get:quadruped.BatteryState.current)
  return _internal_current();
}
inline void BatteryState::_internal_set_current(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000004u;
  current_ = value;
}
inline void BatteryState::set_current(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_current(value);
  // @@protoc_insertion_point(field_set:quadruped.BatteryState.current)
}

// optional int32 cycle = 4;
inline bool BatteryState::_internal_has_cycle() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool BatteryState::has_cycle() const {
  return _internal_has_cycle();
}
inline void BatteryState::clear_cycle() {
  cycle_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 BatteryState::_internal_cycle() const {
  return cycle_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 BatteryState::cycle() const {
  // @@protoc_insertion_point(field_get:quadruped.BatteryState.cycle)
  return _internal_cycle();
}
inline void BatteryState::_internal_set_cycle(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000008u;
  cycle_ = value;
}
inline void BatteryState::set_cycle(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_cycle(value);
  // @@protoc_insertion_point(field_set:quadruped.BatteryState.cycle)
}

// -------------------------------------------------------------------

// IMUState

// repeated float quaternion = 1 [packed = true];
inline int IMUState::_internal_quaternion_size() const {
  return quaternion_.size();
}
inline int IMUState::quaternion_size() const {
  return _internal_quaternion_size();
}
inline void IMUState::clear_quaternion() {
  quaternion_.Clear();
}
inline float IMUState::_internal_quaternion(int index) const {
  return quaternion_.Get(index);
}
inline float IMUState::quaternion(int index) const {
  // @@protoc_insertion_point(field_get:quadruped.IMUState.quaternion)
  return _internal_quaternion(index);
}
inline void IMUState::set_quaternion(int index, float value) {
  quaternion_.Set(index, value);
  // @@protoc_insertion_point(field_set:quadruped.IMUState.quaternion)
}
inline void IMUState::_internal_add_quaternion(float value) {
  quaternion_.Add(value);
}
inline void IMUState::add_quaternion(float value) {
  _internal_add_quaternion(value);
  // @@protoc_insertion_point(field_add:quadruped.IMUState.quaternion)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
IMUState::_internal_quaternion() const {
  return quaternion_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
IMUState::quaternion() const {
  // @@protoc_insertion_point(field_list:quadruped.IMUState.quaternion)
  return _internal_quaternion();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
IMUState::_internal_mutable_quaternion() {
  return &quaternion_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
IMUState::mutable_quaternion() {
  // @@protoc_insertion_point(field_mutable_list:quadruped.IMUState.quaternion)
  return _internal_mutable_quaternion();
}

// repeated float gyroscope = 2 [packed = true];
inline int IMUState::_internal_gyroscope_size() const {
  return gyroscope_.size();
}
inline int IMUState::gyroscope_size() const {
  return _internal_gyroscope_size();
}
inline void IMUState::clear_gyroscope() {
  gyroscope_.Clear();
}
inline float IMUState::_internal_gyroscope(int index) const {
  return gyroscope_.Get(index);
}
inline float IMUState::gyroscope(int index) const {
  // @@protoc_insertion_point(field_get:quadruped.IMUState.gyroscope)
  return _internal_gyroscope(index);
}
inline void IMUState::set_gyroscope(int index, float value) {
  gyroscope_.Set(index, value);
  // @@protoc_insertion_point(field_set:quadruped.IMUState.gyroscope)
}
inline void IMUState::_internal_add_gyroscope(float value) {
  gyroscope_.Add(value);
}
inline void IMUState::add_gyroscope(float value) {
  _internal_add_gyroscope(value);
  // @@protoc_insertion_point(field_add:quadruped.IMUState.gyroscope)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
IMUState::_internal_gyroscope() const {
  return gyroscope_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
IMUState::gyroscope() const {
  // @@protoc_insertion_point(field_list:quadruped.IMUState.gyroscope)
  return _internal_gyroscope();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
IMUState::_internal_mutable_gyroscope() {
  return &gyroscope_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
IMUState::mutable_gyroscope() {
  // @@protoc_insertion_point(field_mutable_list:quadruped.IMUState.gyroscope)
  return _internal_mutable_gyroscope();
}

// repeated float accelerometer = 3 [packed = true];
inline int IMUState::_internal_accelerometer_size() const {
  return accelerometer_.size();
}
inline int IMUState::accelerometer_size() const {
  return _internal_accelerometer_size();
}
inline void IMUState::clear_accelerometer() {
  accelerometer_.Clear();
}
inline float IMUState::_internal_accelerometer(int index) const {
  return accelerometer_.Get(index);
}
inline float IMUState::accelerometer(int index) const {
  // @@protoc_insertion_point(field_get:quadruped.IMUState.accelerometer)
  return _internal_accelerometer(index);
}
inline void IMUState::set_accelerometer(int index, float value) {
  accelerometer_.Set(index, value);
  // @@protoc_insertion_point(field_set:quadruped.IMUState.accelerometer)
}
inline void IMUState::_internal_add_accelerometer(float value) {
  accelerometer_.Add(value);
}
inline void IMUState::add_accelerometer(float value) {
  _internal_add_accelerometer(value);
  // @@protoc_insertion_point(field_add:quadruped.IMUState.accelerometer)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
IMUState::_internal_accelerometer() const {
  return accelerometer_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
IMUState::accelerometer() const {
  // @@protoc_insertion_point(field_list:quadruped.IMUState.accelerometer)
  return _internal_accelerometer();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
IMUState::_internal_mutable_accelerometer() {
  return &accelerometer_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
IMUState::mutable_accelerometer() {
  // @@protoc_insertion_point(field_mutable_list:quadruped.IMUState.accelerometer)
  return _internal_mutable_accelerometer();
}

// repeated float rpy = 4 [packed = true];
inline int IMUState::_internal_rpy_size() const {
  return rpy_.size();
}
inline int IMUState::rpy_size() const {
  return _internal_rpy_size();
}
inline void IMUState::clear_rpy() {
  rpy_.Clear();
}
inline float IMUState::_internal_rpy(int index) const {
  return rpy_.Get(index);
}
inline float IMUState::rpy(int index) const {
  // @@protoc_insertion_point(field_get:quadruped.IMUState.rpy)
  return _internal_rpy(index);
}
inline void IMUState::set_rpy(int index, float value) {
  rpy_.Set(index, value);
  // @@protoc_insertion_point(field_set:quadruped.IMUState.rpy)
}
inline void IMUState::_internal_add_rpy(float value) {
  rpy_.Add(value);
}
inline void IMUState::add_rpy(float value) {
  _internal_add_rpy(value);
  // @@protoc_insertion_point(field_add:quadruped.IMUState.rpy)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
IMUState::_internal_rpy() const {
  return rpy_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
IMUState::rpy() const {
  // @@protoc_insertion_point(field_list:quadruped.IMUState.rpy)
  return _internal_rpy();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
IMUState::_internal_mutable_rpy() {
  return &rpy_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
IMUState::mutable_rpy() {
  // @@protoc_insertion_point(field_mutable_list:quadruped.IMUState.rpy)
  return _internal_mutable_rpy();
}

// optional int32 temperature = 5;
inline bool IMUState::_internal_has_temperature() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool IMUState::has_temperature() const {
  return _internal_has_temperature();
}
inline void IMUState::clear_temperature() {
  temperature_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 IMUState::_internal_temperature() const {
  return temperature_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 IMUState::temperature() const {
  // @@protoc_insertion_point(field_get:quadruped.IMUState.temperature)
  return _internal_temperature();
}
inline void IMUState::_internal_set_temperature(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000001u;
  temperature_ = value;
}
inline void IMUState::set_temperature(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_temperature(value);
  // @@protoc_insertion_point(field_set:quadruped.IMUState.temperature)
}

// -------------------------------------------------------------------

// GlobalLocation

// repeated float position = 1 [packed = true];
inline int GlobalLocation::_internal_position_size() const {
  return position_.size();
}
inline int GlobalLocation::position_size() const {
  return _internal_position_size();
}
inline void GlobalLocation::clear_position() {
  position_.Clear();
}
inline float GlobalLocation::_internal_position(int index) const {
  return position_.Get(index);
}
inline float GlobalLocation::position(int index) const {
  // @@protoc_insertion_point(field_get:quadruped.GlobalLocation.position)
  return _internal_position(index);
}
inline void GlobalLocation::set_position(int index, float value) {
  position_.Set(index, value);
  // @@protoc_insertion_point(field_set:quadruped.GlobalLocation.position)
}
inline void GlobalLocation::_internal_add_position(float value) {
  position_.Add(value);
}
inline void GlobalLocation::add_position(float value) {
  _internal_add_position(value);
  // @@protoc_insertion_point(field_add:quadruped.GlobalLocation.position)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
GlobalLocation::_internal_position() const {
  return position_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
GlobalLocation::position() const {
  // @@protoc_insertion_point(field_list:quadruped.GlobalLocation.position)
  return _internal_position();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
GlobalLocation::_internal_mutable_position() {
  return &position_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
GlobalLocation::mutable_position() {
  // @@protoc_insertion_point(field_mutable_list:quadruped.GlobalLocation.position)
  return _internal_mutable_position();
}

// repeated float velocity = 2 [packed = true];
inline int GlobalLocation::_internal_velocity_size() const {
  return velocity_.size();
}
inline int GlobalLocation::velocity_size() const {
  return _internal_velocity_size();
}
inline void GlobalLocation::clear_velocity() {
  velocity_.Clear();
}
inline float GlobalLocation::_internal_velocity(int index) const {
  return velocity_.Get(index);
}
inline float GlobalLocation::velocity(int index) const {
  // @@protoc_insertion_point(field_get:quadruped.GlobalLocation.velocity)
  return _internal_velocity(index);
}
inline void GlobalLocation::set_velocity(int index, float value) {
  velocity_.Set(index, value);
  // @@protoc_insertion_point(field_set:quadruped.GlobalLocation.velocity)
}
inline void GlobalLocation::_internal_add_velocity(float value) {
  velocity_.Add(value);
}
inline void GlobalLocation::add_velocity(float value) {
  _internal_add_velocity(value);
  // @@protoc_insertion_point(field_add:quadruped.GlobalLocation.velocity)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
GlobalLocation::_internal_velocity() const {
  return velocity_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
GlobalLocation::velocity() const {
  // @@protoc_insertion_point(field_list:quadruped.GlobalLocation.velocity)
  return _internal_velocity();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
GlobalLocation::_internal_mutable_velocity() {
  return &velocity_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
GlobalLocation::mutable_velocity() {
  // @@protoc_insertion_point(field_mutable_list:quadruped.GlobalLocation.velocity)
  return _internal_mutable_velocity();
}

// optional float yaw_speed = 3;
inline bool GlobalLocation::_internal_has_yaw_speed() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool GlobalLocation::has_yaw_speed() const {
  return _internal_has_yaw_speed();
}
inline void GlobalLocation::clear_yaw_speed() {
  yaw_speed_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline float GlobalLocation::_internal_yaw_speed() const {
  return yaw_speed_;
}
inline float GlobalLocation::yaw_speed() const {
  // @@protoc_insertion_point(field_get:quadruped.GlobalLocation.yaw_speed)
  return _internal_yaw_speed();
}
inline void GlobalLocation::_internal_set_yaw_speed(float value) {
  _has_bits_[0] |= 0x00000001u;
  yaw_speed_ = value;
}
inline void GlobalLocation::set_yaw_speed(float value) {
  _internal_set_yaw_speed(value);
  // @@protoc_insertion_point(field_set:quadruped.GlobalLocation.yaw_speed)
}

// -------------------------------------------------------------------

// BodyLocation

// repeated int32 foot_force = 1 [packed = true];
inline int BodyLocation::_internal_foot_force_size() const {
  return foot_force_.size();
}
inline int BodyLocation::foot_force_size() const {
  return _internal_foot_force_size();
}
inline void BodyLocation::clear_foot_force() {
  foot_force_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::int32 BodyLocation::_internal_foot_force(int index) const {
  return foot_force_.Get(index);
}
inline ::PROTOBUF_NAMESPACE_ID::int32 BodyLocation::foot_force(int index) const {
  // @@protoc_insertion_point(field_get:quadruped.BodyLocation.foot_force)
  return _internal_foot_force(index);
}
inline void BodyLocation::set_foot_force(int index, ::PROTOBUF_NAMESPACE_ID::int32 value) {
  foot_force_.Set(index, value);
  // @@protoc_insertion_point(field_set:quadruped.BodyLocation.foot_force)
}
inline void BodyLocation::_internal_add_foot_force(::PROTOBUF_NAMESPACE_ID::int32 value) {
  foot_force_.Add(value);
}
inline void BodyLocation::add_foot_force(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_add_foot_force(value);
  // @@protoc_insertion_point(field_add:quadruped.BodyLocation.foot_force)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
BodyLocation::_internal_foot_force() const {
  return foot_force_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
BodyLocation::foot_force() const {
  // @@protoc_insertion_point(field_list:quadruped.BodyLocation.foot_force)
  return _internal_foot_force();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
BodyLocation::_internal_mutable_foot_force() {
  return &foot_force_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
BodyLocation::mutable_foot_force() {
  // @@protoc_insertion_point(field_mutable_list:quadruped.BodyLocation.foot_force)
  return _internal_mutable_foot_force();
}

// optional float body_height = 2;
inline bool BodyLocation::_internal_has_body_height() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool BodyLocation::has_body_height() const {
  return _internal_has_body_height();
}
inline void BodyLocation::clear_body_height() {
  body_height_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline float BodyLocation::_internal_body_height() const {
  return body_height_;
}
inline float BodyLocation::body_height() const {
  // @@protoc_insertion_point(field_get:quadruped.BodyLocation.body_height)
  return _internal_body_height();
}
inline void BodyLocation::_internal_set_body_height(float value) {
  _has_bits_[0] |= 0x00000001u;
  body_height_ = value;
}
inline void BodyLocation::set_body_height(float value) {
  _internal_set_body_height(value);
  // @@protoc_insertion_point(field_set:quadruped.BodyLocation.body_height)
}

// repeated float foot_position_body = 3 [packed = true];
inline int BodyLocation::_internal_foot_position_body_size() const {
  return foot_position_body_.size();
}
inline int BodyLocation::foot_position_body_size() const {
  return _internal_foot_position_body_size();
}
inline void BodyLocation::clear_foot_position_body() {
  foot_position_body_.Clear();
}
inline float BodyLocation::_internal_foot_position_body(int index) const {
  return foot_position_body_.Get(index);
}
inline float BodyLocation::foot_position_body(int index) const {
  // @@protoc_insertion_point(field_get:quadruped.BodyLocation.foot_position_body)
  return _internal_foot_position_body(index);
}
inline void BodyLocation::set_foot_position_body(int index, float value) {
  foot_position_body_.Set(index, value);
  // @@protoc_insertion_point(field_set:quadruped.BodyLocation.foot_position_body)
}
inline void BodyLocation::_internal_add_foot_position_body(float value) {
  foot_position_body_.Add(value);
}
inline void BodyLocation::add_foot_position_body(float value) {
  _internal_add_foot_position_body(value);
  // @@protoc_insertion_point(field_add:quadruped.BodyLocation.foot_position_body)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
BodyLocation::_internal_foot_position_body() const {
  return foot_position_body_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
BodyLocation::foot_position_body() const {
  // @@protoc_insertion_point(field_list:quadruped.BodyLocation.foot_position_body)
  return _internal_foot_position_body();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
BodyLocation::_internal_mutable_foot_position_body() {
  return &foot_position_body_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
BodyLocation::mutable_foot_position_body() {
  // @@protoc_insertion_point(field_mutable_list:quadruped.BodyLocation.foot_position_body)
  return _internal_mutable_foot_position_body();
}

// repeated float foot_speed_body = 4 [packed = true];
inline int BodyLocation::_internal_foot_speed_body_size() const {
  return foot_speed_body_.size();
}
inline int BodyLocation::foot_speed_body_size() const {
  return _internal_foot_speed_body_size();
}
inline void BodyLocation::clear_foot_speed_body() {
  foot_speed_body_.Clear();
}
inline float BodyLocation::_internal_foot_speed_body(int index) const {
  return foot_speed_body_.Get(index);
}
inline float BodyLocation::foot_speed_body(int index) const {
  // @@protoc_insertion_point(field_get:quadruped.BodyLocation.foot_speed_body)
  return _internal_foot_speed_body(index);
}
inline void BodyLocation::set_foot_speed_body(int index, float value) {
  foot_speed_body_.Set(index, value);
  // @@protoc_insertion_point(field_set:quadruped.BodyLocation.foot_speed_body)
}
inline void BodyLocation::_internal_add_foot_speed_body(float value) {
  foot_speed_body_.Add(value);
}
inline void BodyLocation::add_foot_speed_body(float value) {
  _internal_add_foot_speed_body(value);
  // @@protoc_insertion_point(field_add:quadruped.BodyLocation.foot_speed_body)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
BodyLocation::_internal_foot_speed_body() const {
  return foot_speed_body_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
BodyLocation::foot_speed_body() const {
  // @@protoc_insertion_point(field_list:quadruped.BodyLocation.foot_speed_body)
  return _internal_foot_speed_body();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
BodyLocation::_internal_mutable_foot_speed_body() {
  return &foot_speed_body_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
BodyLocation::mutable_foot_speed_body() {
  // @@protoc_insertion_point(field_mutable_list:quadruped.BodyLocation.foot_speed_body)
  return _internal_mutable_foot_speed_body();
}

// -------------------------------------------------------------------

// StateDatas

// optional bool obstacle_avoid_mode = 1 [default = false];
inline bool StateDatas::_internal_has_obstacle_avoid_mode() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool StateDatas::has_obstacle_avoid_mode() const {
  return _internal_has_obstacle_avoid_mode();
}
inline void StateDatas::clear_obstacle_avoid_mode() {
  obstacle_avoid_mode_ = false;
  _has_bits_[0] &= ~0x00000020u;
}
inline bool StateDatas::_internal_obstacle_avoid_mode() const {
  return obstacle_avoid_mode_;
}
inline bool StateDatas::obstacle_avoid_mode() const {
  // @@protoc_insertion_point(field_get:quadruped.StateDatas.obstacle_avoid_mode)
  return _internal_obstacle_avoid_mode();
}
inline void StateDatas::_internal_set_obstacle_avoid_mode(bool value) {
  _has_bits_[0] |= 0x00000020u;
  obstacle_avoid_mode_ = value;
}
inline void StateDatas::set_obstacle_avoid_mode(bool value) {
  _internal_set_obstacle_avoid_mode(value);
  // @@protoc_insertion_point(field_set:quadruped.StateDatas.obstacle_avoid_mode)
}

// optional string sport_mode = 2 [default = "normal"];
inline bool StateDatas::_internal_has_sport_mode() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool StateDatas::has_sport_mode() const {
  return _internal_has_sport_mode();
}
inline void StateDatas::clear_sport_mode() {
  sport_mode_.ClearToDefault(::quadruped::StateDatas::_i_give_permission_to_break_this_code_default_sport_mode_, GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& StateDatas::sport_mode() const {
  // @@protoc_insertion_point(field_get:quadruped.StateDatas.sport_mode)
  if (sport_mode_.IsDefault(nullptr)) return _i_give_permission_to_break_this_code_default_sport_mode_.get();
  return _internal_sport_mode();
}
inline void StateDatas::set_sport_mode(const std::string& value) {
  _internal_set_sport_mode(value);
  // @@protoc_insertion_point(field_set:quadruped.StateDatas.sport_mode)
}
inline std::string* StateDatas::mutable_sport_mode() {
  // @@protoc_insertion_point(field_mutable:quadruped.StateDatas.sport_mode)
  return _internal_mutable_sport_mode();
}
inline const std::string& StateDatas::_internal_sport_mode() const {
  return sport_mode_.Get();
}
inline void StateDatas::_internal_set_sport_mode(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  sport_mode_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::NonEmptyDefault{}, value, GetArena());
}
inline void StateDatas::set_sport_mode(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  sport_mode_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::NonEmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:quadruped.StateDatas.sport_mode)
}
inline void StateDatas::set_sport_mode(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  sport_mode_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::NonEmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:quadruped.StateDatas.sport_mode)
}
inline void StateDatas::set_sport_mode(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  sport_mode_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::NonEmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:quadruped.StateDatas.sport_mode)
}
inline std::string* StateDatas::_internal_mutable_sport_mode() {
  _has_bits_[0] |= 0x00000001u;
  return sport_mode_.Mutable(::quadruped::StateDatas::_i_give_permission_to_break_this_code_default_sport_mode_, GetArena());
}
inline std::string* StateDatas::release_sport_mode() {
  // @@protoc_insertion_point(field_release:quadruped.StateDatas.sport_mode)
  if (!_internal_has_sport_mode()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return sport_mode_.ReleaseNonDefault(nullptr, GetArena());
}
inline void StateDatas::set_allocated_sport_mode(std::string* sport_mode) {
  if (sport_mode != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  sport_mode_.SetAllocated(nullptr, sport_mode,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:quadruped.StateDatas.sport_mode)
}

// optional int32 high_level_mode = 3 [default = 0];
inline bool StateDatas::_internal_has_high_level_mode() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool StateDatas::has_high_level_mode() const {
  return _internal_has_high_level_mode();
}
inline void StateDatas::clear_high_level_mode() {
  high_level_mode_ = 0;
  _has_bits_[0] &= ~0x00000040u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 StateDatas::_internal_high_level_mode() const {
  return high_level_mode_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 StateDatas::high_level_mode() const {
  // @@protoc_insertion_point(field_get:quadruped.StateDatas.high_level_mode)
  return _internal_high_level_mode();
}
inline void StateDatas::_internal_set_high_level_mode(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000040u;
  high_level_mode_ = value;
}
inline void StateDatas::set_high_level_mode(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_high_level_mode(value);
  // @@protoc_insertion_point(field_set:quadruped.StateDatas.high_level_mode)
}

// optional float foot_raise_height = 5 [default = 0];
inline bool StateDatas::_internal_has_foot_raise_height() const {
  bool value = (_has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool StateDatas::has_foot_raise_height() const {
  return _internal_has_foot_raise_height();
}
inline void StateDatas::clear_foot_raise_height() {
  foot_raise_height_ = 0;
  _has_bits_[0] &= ~0x00000080u;
}
inline float StateDatas::_internal_foot_raise_height() const {
  return foot_raise_height_;
}
inline float StateDatas::foot_raise_height() const {
  // @@protoc_insertion_point(field_get:quadruped.StateDatas.foot_raise_height)
  return _internal_foot_raise_height();
}
inline void StateDatas::_internal_set_foot_raise_height(float value) {
  _has_bits_[0] |= 0x00000080u;
  foot_raise_height_ = value;
}
inline void StateDatas::set_foot_raise_height(float value) {
  _internal_set_foot_raise_height(value);
  // @@protoc_insertion_point(field_set:quadruped.StateDatas.foot_raise_height)
}

// optional int32 gait_type = 6 [default = 0];
inline bool StateDatas::_internal_has_gait_type() const {
  bool value = (_has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline bool StateDatas::has_gait_type() const {
  return _internal_has_gait_type();
}
inline void StateDatas::clear_gait_type() {
  gait_type_ = 0;
  _has_bits_[0] &= ~0x00000100u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 StateDatas::_internal_gait_type() const {
  return gait_type_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 StateDatas::gait_type() const {
  // @@protoc_insertion_point(field_get:quadruped.StateDatas.gait_type)
  return _internal_gait_type();
}
inline void StateDatas::_internal_set_gait_type(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000100u;
  gait_type_ = value;
}
inline void StateDatas::set_gait_type(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_gait_type(value);
  // @@protoc_insertion_point(field_set:quadruped.StateDatas.gait_type)
}

// optional .quadruped.BatteryState battery_state = 7;
inline bool StateDatas::_internal_has_battery_state() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || battery_state_ != nullptr);
  return value;
}
inline bool StateDatas::has_battery_state() const {
  return _internal_has_battery_state();
}
inline void StateDatas::clear_battery_state() {
  if (battery_state_ != nullptr) battery_state_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::quadruped::BatteryState& StateDatas::_internal_battery_state() const {
  const ::quadruped::BatteryState* p = battery_state_;
  return p != nullptr ? *p : reinterpret_cast<const ::quadruped::BatteryState&>(
      ::quadruped::_BatteryState_default_instance_);
}
inline const ::quadruped::BatteryState& StateDatas::battery_state() const {
  // @@protoc_insertion_point(field_get:quadruped.StateDatas.battery_state)
  return _internal_battery_state();
}
inline void StateDatas::unsafe_arena_set_allocated_battery_state(
    ::quadruped::BatteryState* battery_state) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(battery_state_);
  }
  battery_state_ = battery_state;
  if (battery_state) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:quadruped.StateDatas.battery_state)
}
inline ::quadruped::BatteryState* StateDatas::release_battery_state() {
  _has_bits_[0] &= ~0x00000002u;
  ::quadruped::BatteryState* temp = battery_state_;
  battery_state_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::quadruped::BatteryState* StateDatas::unsafe_arena_release_battery_state() {
  // @@protoc_insertion_point(field_release:quadruped.StateDatas.battery_state)
  _has_bits_[0] &= ~0x00000002u;
  ::quadruped::BatteryState* temp = battery_state_;
  battery_state_ = nullptr;
  return temp;
}
inline ::quadruped::BatteryState* StateDatas::_internal_mutable_battery_state() {
  _has_bits_[0] |= 0x00000002u;
  if (battery_state_ == nullptr) {
    auto* p = CreateMaybeMessage<::quadruped::BatteryState>(GetArena());
    battery_state_ = p;
  }
  return battery_state_;
}
inline ::quadruped::BatteryState* StateDatas::mutable_battery_state() {
  // @@protoc_insertion_point(field_mutable:quadruped.StateDatas.battery_state)
  return _internal_mutable_battery_state();
}
inline void StateDatas::set_allocated_battery_state(::quadruped::BatteryState* battery_state) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete battery_state_;
  }
  if (battery_state) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(battery_state);
    if (message_arena != submessage_arena) {
      battery_state = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, battery_state, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  battery_state_ = battery_state;
  // @@protoc_insertion_point(field_set_allocated:quadruped.StateDatas.battery_state)
}

// optional .quadruped.IMUState imu_state = 8;
inline bool StateDatas::_internal_has_imu_state() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || imu_state_ != nullptr);
  return value;
}
inline bool StateDatas::has_imu_state() const {
  return _internal_has_imu_state();
}
inline void StateDatas::clear_imu_state() {
  if (imu_state_ != nullptr) imu_state_->Clear();
  _has_bits_[0] &= ~0x00000004u;
}
inline const ::quadruped::IMUState& StateDatas::_internal_imu_state() const {
  const ::quadruped::IMUState* p = imu_state_;
  return p != nullptr ? *p : reinterpret_cast<const ::quadruped::IMUState&>(
      ::quadruped::_IMUState_default_instance_);
}
inline const ::quadruped::IMUState& StateDatas::imu_state() const {
  // @@protoc_insertion_point(field_get:quadruped.StateDatas.imu_state)
  return _internal_imu_state();
}
inline void StateDatas::unsafe_arena_set_allocated_imu_state(
    ::quadruped::IMUState* imu_state) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(imu_state_);
  }
  imu_state_ = imu_state;
  if (imu_state) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:quadruped.StateDatas.imu_state)
}
inline ::quadruped::IMUState* StateDatas::release_imu_state() {
  _has_bits_[0] &= ~0x00000004u;
  ::quadruped::IMUState* temp = imu_state_;
  imu_state_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::quadruped::IMUState* StateDatas::unsafe_arena_release_imu_state() {
  // @@protoc_insertion_point(field_release:quadruped.StateDatas.imu_state)
  _has_bits_[0] &= ~0x00000004u;
  ::quadruped::IMUState* temp = imu_state_;
  imu_state_ = nullptr;
  return temp;
}
inline ::quadruped::IMUState* StateDatas::_internal_mutable_imu_state() {
  _has_bits_[0] |= 0x00000004u;
  if (imu_state_ == nullptr) {
    auto* p = CreateMaybeMessage<::quadruped::IMUState>(GetArena());
    imu_state_ = p;
  }
  return imu_state_;
}
inline ::quadruped::IMUState* StateDatas::mutable_imu_state() {
  // @@protoc_insertion_point(field_mutable:quadruped.StateDatas.imu_state)
  return _internal_mutable_imu_state();
}
inline void StateDatas::set_allocated_imu_state(::quadruped::IMUState* imu_state) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete imu_state_;
  }
  if (imu_state) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(imu_state);
    if (message_arena != submessage_arena) {
      imu_state = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, imu_state, submessage_arena);
    }
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  imu_state_ = imu_state;
  // @@protoc_insertion_point(field_set_allocated:quadruped.StateDatas.imu_state)
}

// optional .quadruped.GlobalLocation global_location = 9;
inline bool StateDatas::_internal_has_global_location() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  PROTOBUF_ASSUME(!value || global_location_ != nullptr);
  return value;
}
inline bool StateDatas::has_global_location() const {
  return _internal_has_global_location();
}
inline void StateDatas::clear_global_location() {
  if (global_location_ != nullptr) global_location_->Clear();
  _has_bits_[0] &= ~0x00000008u;
}
inline const ::quadruped::GlobalLocation& StateDatas::_internal_global_location() const {
  const ::quadruped::GlobalLocation* p = global_location_;
  return p != nullptr ? *p : reinterpret_cast<const ::quadruped::GlobalLocation&>(
      ::quadruped::_GlobalLocation_default_instance_);
}
inline const ::quadruped::GlobalLocation& StateDatas::global_location() const {
  // @@protoc_insertion_point(field_get:quadruped.StateDatas.global_location)
  return _internal_global_location();
}
inline void StateDatas::unsafe_arena_set_allocated_global_location(
    ::quadruped::GlobalLocation* global_location) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(global_location_);
  }
  global_location_ = global_location;
  if (global_location) {
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:quadruped.StateDatas.global_location)
}
inline ::quadruped::GlobalLocation* StateDatas::release_global_location() {
  _has_bits_[0] &= ~0x00000008u;
  ::quadruped::GlobalLocation* temp = global_location_;
  global_location_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::quadruped::GlobalLocation* StateDatas::unsafe_arena_release_global_location() {
  // @@protoc_insertion_point(field_release:quadruped.StateDatas.global_location)
  _has_bits_[0] &= ~0x00000008u;
  ::quadruped::GlobalLocation* temp = global_location_;
  global_location_ = nullptr;
  return temp;
}
inline ::quadruped::GlobalLocation* StateDatas::_internal_mutable_global_location() {
  _has_bits_[0] |= 0x00000008u;
  if (global_location_ == nullptr) {
    auto* p = CreateMaybeMessage<::quadruped::GlobalLocation>(GetArena());
    global_location_ = p;
  }
  return global_location_;
}
inline ::quadruped::GlobalLocation* StateDatas::mutable_global_location() {
  // @@protoc_insertion_point(field_mutable:quadruped.StateDatas.global_location)
  return _internal_mutable_global_location();
}
inline void StateDatas::set_allocated_global_location(::quadruped::GlobalLocation* global_location) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete global_location_;
  }
  if (global_location) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(global_location);
    if (message_arena != submessage_arena) {
      global_location = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, global_location, submessage_arena);
    }
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  global_location_ = global_location;
  // @@protoc_insertion_point(field_set_allocated:quadruped.StateDatas.global_location)
}

// optional .quadruped.BodyLocation body_location = 10;
inline bool StateDatas::_internal_has_body_location() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  PROTOBUF_ASSUME(!value || body_location_ != nullptr);
  return value;
}
inline bool StateDatas::has_body_location() const {
  return _internal_has_body_location();
}
inline void StateDatas::clear_body_location() {
  if (body_location_ != nullptr) body_location_->Clear();
  _has_bits_[0] &= ~0x00000010u;
}
inline const ::quadruped::BodyLocation& StateDatas::_internal_body_location() const {
  const ::quadruped::BodyLocation* p = body_location_;
  return p != nullptr ? *p : reinterpret_cast<const ::quadruped::BodyLocation&>(
      ::quadruped::_BodyLocation_default_instance_);
}
inline const ::quadruped::BodyLocation& StateDatas::body_location() const {
  // @@protoc_insertion_point(field_get:quadruped.StateDatas.body_location)
  return _internal_body_location();
}
inline void StateDatas::unsafe_arena_set_allocated_body_location(
    ::quadruped::BodyLocation* body_location) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(body_location_);
  }
  body_location_ = body_location;
  if (body_location) {
    _has_bits_[0] |= 0x00000010u;
  } else {
    _has_bits_[0] &= ~0x00000010u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:quadruped.StateDatas.body_location)
}
inline ::quadruped::BodyLocation* StateDatas::release_body_location() {
  _has_bits_[0] &= ~0x00000010u;
  ::quadruped::BodyLocation* temp = body_location_;
  body_location_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::quadruped::BodyLocation* StateDatas::unsafe_arena_release_body_location() {
  // @@protoc_insertion_point(field_release:quadruped.StateDatas.body_location)
  _has_bits_[0] &= ~0x00000010u;
  ::quadruped::BodyLocation* temp = body_location_;
  body_location_ = nullptr;
  return temp;
}
inline ::quadruped::BodyLocation* StateDatas::_internal_mutable_body_location() {
  _has_bits_[0] |= 0x00000010u;
  if (body_location_ == nullptr) {
    auto* p = CreateMaybeMessage<::quadruped::BodyLocation>(GetArena());
    body_location_ = p;
  }
  return body_location_;
}
inline ::quadruped::BodyLocation* StateDatas::mutable_body_location() {
  // @@protoc_insertion_point(field_mutable:quadruped.StateDatas.body_location)
  return _internal_mutable_body_location();
}
inline void StateDatas::set_allocated_body_location(::quadruped::BodyLocation* body_location) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete body_location_;
  }
  if (body_location) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(body_location);
    if (message_arena != submessage_arena) {
      body_location = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, body_location, submessage_arena);
    }
    _has_bits_[0] |= 0x00000010u;
  } else {
    _has_bits_[0] &= ~0x00000010u;
  }
  body_location_ = body_location;
  // @@protoc_insertion_point(field_set_allocated:quadruped.StateDatas.body_location)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace quadruped

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_proto_2fstate_5fdatas_2eproto
